routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::group(['middleware' => 'auth'], function () {

    // Projects

    Route::get('project/index', 'ProjectController@index')->name('project.index');
    //Route::get('project/create', 'ProjectController@create')->name('project.create');
    Route::get('project/list', 'ProjectController@getList')->name('project.list');

    Route::resource('project', 'ProjectController', ['except' => ['show']]);


    // Users
    //Route::group(['middleware' => 'group:1'], function()
    //{
        Route::resource('user', 'UserController', ['except' => ['show']]);
    //});


    Route::get('user/get-list', 'UserController@getList')->name('user.get-list');
    Route::post('user/change-group', 'UserController@changeContributorGroup')->name('user.change-group');
    Route::post('user/change-project', 'UserController@changeProject')->name('user.change-project');

    // Groups
    Route::resource('group', 'GroupController', ['except' => ['show']]);
    Route::get('group/get-list', 'GroupController@getList')->name('group.get-list');



    Route::get('report-schedule/createMultiple', 'Report\ReportScheduleController@createMultiple');
//    Route::get('report-schedule', 'ReportScheduleController@index')->name('report_schedule.index');
    Route::get('report-schedule/report/{id}', 'ReportScheduleController@index')->name('report_schedule.index');
    Route::get('report-schedule/list', 'ReportScheduleController@getList')->name('report_schedule.list');
    Route::get('report-schedule/getMiniStat', 'Report\ReportScheduleController@getMiniStat');

    Route::resource('report-schedule', 'ReportScheduleController', ['except' => ['show']]);


    Route::namespace('Dashboard')->prefix('dashboard')->group(function () {

        Route::get('media', 'MediaController@index')->name('dashboard.media');
        Route::get('press', 'PressController@index')->name('dashboard.press');
        Route::get('test', 'MediaController@test');
        Route::resource('dashboard', 'DashboardController');

    });


    Route::namespace('Report')->prefix('report-schedule')->group(function () {

        //Reports
        Route::get('grid/{index}', 'ReportScheduleController@grid')->name('report-schedule/grid');
        Route::any('get-data', 'ReportScheduleController@getData')->name('report-schedule.get-data');
        Route::post('add-row', 'ReportScheduleController@addRow')->name('report-schedule.add-row');
        Route::post('remove-row', 'ReportScheduleController@removeRow')->name('report-schedule.remove-row');
        Route::post('insert-data', 'ReportScheduleController@insertData')->name('report-schedule.insert-data');
        Route::post('change-status/{id}', 'ReportScheduleController@changeStatus')->name('report-schedule.change-status');
        Route::post('generateNewRow', 'ReportScheduleController@generateNewRow');
        Route::any('getData/{reportSchedule_id}', 'ReportScheduleController@getData');

        Route::get('destroy/{id}', 'ReportScheduleController@destroy')->name('report-schedule.destroy');

    });


    Route::namespace('Report')->prefix('report')->group(function () {

        Route::get('/', 'ReportController@index')->name('report.index');
        Route::get('destroy/{id}', 'ReportController@destroy')->name('report.destroy');

        // Report
        Route::resource('report', 'ReportController', ['except' => ['index','show', 'edit','update']]);

        // Report columns
        Route::resource('column', 'ReportColumnController', ['as' => 'report','except' => ['show']]);
        Route::get('column/get-list', 'ReportColumnController@getList')->name('report.column.get-list');

        // Report columns lists
        Route::resource('database', 'MyDatabaseController', ['as' => 'report','except' => ['show']]);
        Route::get('database/get-list', 'MyDatabaseController@getList')->name('report.database.get-list');
        Route::get('database/fill/{id}', 'MyDatabaseController@fill')->name('report.database.fill');
        Route::post('database/get-data', 'MyDatabaseController@getData')->name('report.database.get-data');
        Route::post('database/insert-data', 'MyDatabaseController@insertData')->name('report.database.insert-data');
        Route::post('database/remove-row', 'MyDatabaseController@removeRow')->name('report.database.remove-row');
        Route::post('database/generateNewRow', 'MyDatabaseController@generateNewRow');

        Route::any('database/getItems/{field}', 'MyDatabaseController@getItems');


        Route::any('database/getData/{db_id}', 'MyDatabaseController@getData')->name('report.database.get-data');


        // Report templates
        Route::resource('template', 'ReportTemplateController', ['as' => 'report','except' => ['show']]);
        Route::get('template/get-list', 'ReportTemplateController@getList')->name('report.template.get-list');
    });

    Route::namespace('Report')->prefix('reportFinal')->group(function () {

        Route::get('/list', 'ReportFinalController@getList');
        Route::get('/addNew', 'ReportFinalController@addNew');
        Route::resource('/', 'ReportFinalController');

    });

    Route::namespace('Import')->prefix('import')->group(function () {


        Route::get('importMediaByContries', 'ImportMediaByCountriesController@importMediaByCountries');
    });

    Route::namespace('presentation')->prefix('presentation')->group(function () {

        Route::get('generatePresentation', 'IFA_Berlin_2017_Controller@init');
    });
});

app/Models/Project.php
<?php

namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model as Model;
use Yajra\Datatables\Facades\Datatables;
use Illuminate\Support\Facades\Validator;

class Project extends \Moloquent
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name'
    ];

    private $rules = [
        'name' => 'required|max:255',
    ];

    public static function getList()
    {

        //$query = $this->select('*')->get();
        //$query = self::select('*')->where('type', '!=', 'main')->get();
        $query = self::select('*')->get();

        //print_r($query);exit;
        return $query;
    }



    public function users()
    {
        return $this->hasMany('App\Models\User');
    }

    public function datatables($data)
    {
        $editable = true;
        $deletable = true;

        return Datatables::of($data)
            ->addColumn('action', function ($item) use($editable, $deletable) {
                return $this->_generateActions($item, $editable, $deletable);
            })
            ->filterColumn('name', function($query, $keyword) {
                $query->where('name', 'like', '%'.$keyword.'%');
            })
            ->make(true);
    }

    public function validate($data)
    {
        if(!$data) {
            return false;
        }

        $v = Validator::make($data, $this->rules);
        $v->validate();
        if ($v->fails()) {
            return false;
        }
        return true;
    }

    private function _generateActions($item, $editable, $deletable)
    {
        $view = view('partials.table_actions', ['item' => $item, 'route' => 'project', 'editable' => $editable, 'deletable' => $deletable]);
        return $view->render();

    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;


class ProjectController extends Controller
{


    public function create()
    {
        return view('project.create');
    }


    /**
     * Show the profile for the given user.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //return view('user.profile', ['user' => Project::findOrFail($id)]);
    }



    public function index()
    {
        return view('project.index');
    }


    public function getList()
    {
        $model = new Project();
        $data = $model->getList();

        return $model->datatables($data);
    }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $model = new Project();
        $data = array();

        foreach ($request->all() as $key => $value)
        {
            $data[$key] = htmlspecialchars( clean( $request->$key, 'noHtml'), ENT_QUOTES );
            $data[$key] = empty($data[$key]) ? null : $data[$key];
        }

        if ($model->validate($data))
            if($model->create($data))
                return redirect()->route('project.index');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Project::findOrFail($id);

        return view('project.edit',compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = Project::findOrFail($id);
        $data = array();

        foreach ($request->all() as $key => $value)
        {
            $data[$key] = is_array($value) ? $request->$key : htmlspecialchars( clean( $request->$key, 'noHtml'), ENT_QUOTES );
            $data[$key] = empty($data[$key]) ? null : $data[$key];
        }

        if ($model->validate($data))
            if($model->update($data))
                return redirect()->route('project.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Project::findOrFail($id);

        $model->delete();

        return redirect()->route('project.index');


        if($model->delete())
            return redirect()->route('project.index');
/*
        if($model->users->isEmpty()){
            if($model->delete())
                return redirect()->route('project.index');
        }
        else{
            return redirect()->route('project.index')->with('error', trans('project.group-has-users'));
        }

        */
    }

}

resources/views/project/create.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
    {{ trans('projects.area') }}
@endsection

@section('contentheader_title')
    {{ trans('projects.area') }}
@endsection

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-12">
                @if(Session::has('errors'))
                    <div class="callout callout-danger">
                        <h4>{{trans('global.errors')}}</h4>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ trans($error) }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{trans('projects.create')}}</h3>
                        <div class="box-tools pull-right">
                            <a href="{{route('group.index')}}" class="btn btn-sm btn-primary">{{trans('projects.cancel')}}</a>
                        </div>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'project.store']) !!}
                        <div class="box-body">
                            <div class="form-group">
                                {!! Form::label('name', trans('projects.name')) !!}
                                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => trans('projects.name-placeholder')]) !!}
                            </div>
                        </div>
                        <div class="box-footer">
                            {!! Form::submit(trans('group.save'),['class' => 'btn btn-primary btn-flat btn-md']) !!}
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/project/edit.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
    {{ trans('project.group') }}
@endsection

@section('contentheader_title')
    {{ trans('project.group') }}
@endsection

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-12">
                @if(Session::has('errors'))
                    <div class="callout callout-danger">
                        <h4>{{trans('global.errors')}}</h4>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ trans($error) }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{trans('group.edit')}}</h3>
                        <div class="box-tools pull-right">
                            <a href="{{route('user.index')}}" class="btn btn-sm btn-primary">{{trans('user.cancel')}}</a>
                        </div>
                    </div>
                    <div class="box-body">
                        {!!Form::model($model,['route' => ['project.update',  $model->getKey()], 'method' => 'put'])!!}
                        <div class="box-body">
                            <div class="form-group">
                                {!! Form::label('name', trans('group.name')) !!}
                                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => trans('project.name-placeholder')]) !!}
                            </div>
                        </div>
                        <div class="box-footer">
                            {!! Form::submit(trans('group.save'),['class' => 'btn btn-primary btn-flat btn-md']) !!}
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/project/index.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
    {{ trans('projects.projects') }}
@endsection

@section('contentheader_title')
    {{ trans('projects.projects') }}
@endsection

@section('js')
    <script type="text/javascript" src="{{asset('js/project.js')}}"></script>
@endsection

@section('main-content')

    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title"></h3>
                        <div class="box-tools pull-right">
                            <a href="{{route('project.create')}}" class="btn btn-sm btn-primary">{{trans('projects.add')}}</a>
                        </div>
                    </div>
                    <div class="box-body">
                        <table class="table table-bordered table-hover dataTable" id="projects-table">
                            <thead>
                            <tr>
                                <th>{{trans('projects.name')}}</th>
                                <th class="table-actions">{{trans('projects.actions')}}</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection