routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::group(['middleware' => 'auth'], function () {

    // Projects

    Route::get('project/index', 'ProjectController@index')->name('project.index');
    //Route::get('project/create', 'ProjectController@create')->name('project.create');
    Route::get('project/list', 'ProjectController@getList')->name('project.list');

    Route::resource('project', 'ProjectController', ['except' => ['show']]);


    // Users
    //Route::group(['middleware' => 'group:1'], function()
    //{
        Route::resource('user', 'UserController', ['except' => ['show']]);
    //});


    Route::get('user/get-list', 'UserController@getList')->name('user.get-list');
    Route::post('user/change-group', 'UserController@changeContributorGroup')->name('user.change-group');
    Route::post('user/change-project', 'UserController@changeProject')->name('user.change-project');

    // Groups
    Route::resource('group', 'GroupController', ['except' => ['show']]);
    Route::get('group/get-list', 'GroupController@getList')->name('group.get-list');



    Route::get('report-schedule/createMultiple', 'Report\ReportScheduleController@createMultiple');
//    Route::get('report-schedule', 'ReportScheduleController@index')->name('report_schedule.index');
    Route::get('report-schedule/report/{id}', 'ReportScheduleController@index')->name('report_schedule.index');
    Route::get('report-schedule/list', 'ReportScheduleController@getList')->name('report_schedule.list');
    Route::get('report-schedule/getMiniStat', 'Report\ReportScheduleController@getMiniStat');

    Route::resource('report-schedule', 'ReportScheduleController', ['except' => ['show']]);


    Route::namespace('Dashboard')->prefix('dashboard')->group(function () {

        Route::get('media', 'MediaController@index')->name('dashboard.media');
        Route::get('press', 'PressController@index')->name('dashboard.press');
        Route::get('test', 'MediaController@test');
        Route::resource('dashboard', 'DashboardController');

    });


    Route::namespace('Report')->prefix('report-schedule')->group(function () {

        //Reports
        Route::get('grid/{index}', 'ReportScheduleController@grid')->name('report-schedule/grid');
        Route::any('get-data', 'ReportScheduleController@getData')->name('report-schedule.get-data');
        Route::post('add-row', 'ReportScheduleController@addRow')->name('report-schedule.add-row');
        Route::post('remove-row', 'ReportScheduleController@removeRow')->name('report-schedule.remove-row');
        Route::post('insert-data', 'ReportScheduleController@insertData')->name('report-schedule.insert-data');
        Route::post('change-status/{id}', 'ReportScheduleController@changeStatus')->name('report-schedule.change-status');
        Route::post('generateNewRow', 'ReportScheduleController@generateNewRow');
        Route::any('getData/{reportSchedule_id}', 'ReportScheduleController@getData');

        Route::get('destroy/{id}', 'ReportScheduleController@destroy')->name('report-schedule.destroy');

    });


    Route::namespace('Report')->prefix('report')->group(function () {

        Route::get('/', 'ReportController@index')->name('report.index');
        Route::get('destroy/{id}', 'ReportController@destroy')->name('report.destroy');

        // Report
        Route::resource('report', 'ReportController', ['except' => ['index','show', 'edit','update']]);

        // Report columns
        Route::resource('column', 'ReportColumnController', ['as' => 'report','except' => ['show']]);
        Route::get('column/get-list', 'ReportColumnController@getList')->name('report.column.get-list');

        // Report columns lists
        Route::resource('database', 'MyDatabaseController', ['as' => 'report','except' => ['show']]);
        Route::get('database/get-list', 'MyDatabaseController@getList')->name('report.database.get-list');
        Route::get('database/fill/{id}', 'MyDatabaseController@fill')->name('report.database.fill');
        Route::post('database/get-data', 'MyDatabaseController@getData')->name('report.database.get-data');
        Route::post('database/insert-data', 'MyDatabaseController@insertData')->name('report.database.insert-data');
        Route::post('database/remove-row', 'MyDatabaseController@removeRow')->name('report.database.remove-row');
        Route::post('database/generateNewRow', 'MyDatabaseController@generateNewRow');

        Route::any('database/getItems/{field}', 'MyDatabaseController@getItems');


        Route::any('database/getData/{db_id}', 'MyDatabaseController@getData')->name('report.database.get-data');


        // Report templates
        Route::resource('template', 'ReportTemplateController', ['as' => 'report','except' => ['show']]);
        Route::get('template/get-list', 'ReportTemplateController@getList')->name('report.template.get-list');
    });

    Route::namespace('Report')->prefix('reportFinal')->group(function () {

        Route::get('/list', 'ReportFinalController@getList');
        Route::get('/addNew', 'ReportFinalController@addNew');
        Route::resource('/', 'ReportFinalController');

    });

    Route::namespace('Import')->prefix('import')->group(function () {


        Route::get('importMediaByContries', 'ImportMediaByCountriesController@importMediaByCountries');
    });

    Route::namespace('presentation')->prefix('presentation')->group(function () {

        Route::get('generatePresentation', 'IFA_Berlin_2017_Controller@init');
    });
});

app/Http/Controllers/Report/MyDatabaseController.php
<?php

namespace App\Http\Controllers\Report;

use App\Http\Controllers\Controller;
use App\Models\Report\MyDatabase;
use App\Models\Report\DatabaseItem;
use Illuminate\Http\Request;
use App\Models\Report\ReportColumn;
use Helper;
use Illuminate\Support\Facades\Session;
use Mockery\Exception;

class MyDatabaseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('my-database.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {




        $fields_tmp = ReportColumn::pluck('title', '_id');
        $fields = [];
        foreach ($fields_tmp as $k => $v) {
            $fields[] = [
                '_id'   => $k,
                'title' => $v,
            ];
        }

        $data = [
            //'model' => $model,
            //'_id' => $model->_id,
            //'title' => $model->title,
            'fields' => $fields,
            'selectedFields' => []
        ];



        return view('my-database.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /*
        $model = new ReportColumnList();
        $data = array();

        foreach ($request->all() as $key => $value){
            if($key == 'fields'){
                if($value){
                    foreach ($value as $k => $v){
                        if($v) {
                            $data[$key][$k] = htmlspecialchars( clean( $v, 'noHtml'), ENT_QUOTES );;
                            $data[$key][$k] = htmlspecialchars( clean( $v, 'noHtml'), ENT_QUOTES );;
                        }

                    }
                }
            }
            else{
                $data[$key] = htmlspecialchars( clean( $request->$key, 'noHtml'), ENT_QUOTES );
                $data[$key] = empty($data[$key]) ? null : $data[$key];
            }
        }

        if ($model->validate($data))
            if($model->create($data))
                return redirect()->route('report.database.index');
*/




        $model = new MyDatabase();
        $model->name = $request->input('name');
        $model->fields = explode('|', $request->input('selectedFields_ser'));

        //echo Helper::shout('now i\'m using my helper class in a controller!!');

        $model->save();
        return redirect()->route('report.database.index');







    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $model = MyDatabase::findOrFail($id);
        //$fields = ReportColumn::pluck('title', '_id');

        //return view('report_template.edit',compact(['model','fields']));


        $fields_tmp = ReportColumn::pluck('title', '_id');
        $fields = [];
        foreach ($fields_tmp as $k => $v) {
            $fields[] = [
                '_id' => $k,
                'title' => $v,
            ];
        }

        /*
                $fieldsStr = [];
                foreach ($model->fields as $f) {
                    $fieldsStr[] = (string)$f;
                }*/

        $selectedFields_tmp = ReportColumn::whereIn('_id', $model->fields)->get();


        $selectedFields_tmp = Helper::getMongoArray($selectedFields_tmp, '_id');


        $selectedFields = [];
        foreach ($model->fields as $fieldId) {
            $selectedFields[] = $selectedFields_tmp[$fieldId];

            // Нужно удалить из списка те, которые уже выбраны, чтобы они не были дважды
            //unset($fields[$f->_id]);

            foreach ($fields as $key2 => $subArr2) {
                if ($subArr2['_id'] == $fieldId) {
                    unset($fields[$key2]);
                }

            }

        }


        /*

                $selectedFields = [];
                foreach ($selectedFields_tmp as $f) {
                    $selectedFields[$f->_id] = $f->title;

                    // Нужно удалить из списка те, которые уже выбраны, чтобы они не были дважды
                    unset($fields[$f->_id]);
                }
        */


        //print_r($selectedFields->toArray());exit;

        //print_r($fields);exit;


        //$fields = ['a'];
        //$selectedFields = $model->fields;

        $data = [
            'model' => $model,
            '_id' => $model->_id,
            'title' => $model->title,
            'fields' => $fields,
            'selectedFields' => $selectedFields
        ];



        return view('my-database.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = MyDatabase::findOrFail($id);
        /*
        $data = array();

        foreach ($request->all() as $key => $value){
            if($key == 'columns'){
                if($value){
                    foreach ($value as $k => $v){
                        if($v)
                            $data[$key][$k] = htmlspecialchars( clean( $v, 'noHtml'), ENT_QUOTES );;
                    }
                }
            }
            else{
                $data[$key] = htmlspecialchars( clean( $request->$key, 'noHtml'), ENT_QUOTES );
                $data[$key] = empty($data[$key]) ? null : $data[$key];
            }
        }

        if ($model->validate($data))
            if($model->update($data))
                return redirect()->route('report.database.index');
        */

        $model->name = $request->input('name');
        $model->fields = explode('|', $request->input('selectedFields_ser'));

        //echo Helper::shout('now i\'m using my helper class in a controller!!');

        $model->save();
        return redirect()->route('report.database.index');





    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //$model = ReportColumnData::findOrFail($id);
//
        //if($model->delete())
           return redirect()->route('report.database.index');
    }

    /**
     * Get data for datatable.
     *
     * @return \Illuminate\Http\Response
     */
    public function getList()
    {

        $model = new MyDatabase();
        $data = $model->getList();

        return $model->datatables($data);
    }

    public function fill($id)
    {
        $MyDatabase = MyDatabase::findOrFail($id);

        // Здесь надо определить какие поля будут Multi-selection select box, т.к. из значения надо передать в шаблон
        $fieldsMultiselect = Helper::prepareFieldsForForm($MyDatabase->fields)['multiselect'];







        return view('my-database.grid', ['model' => $MyDatabase, 'fieldsMultiselect' => $fieldsMultiselect]);
    }

    public function getData(Request $request)
    {

        //print_r($request->all());
        //echo ':::'.$request->db_id;exit;





        $MyDatabase = MyDatabase::findOrFail($request->db_id);
        //$columns = $model->generateColumns();

        //print_r(MyDatabase);exit;


        $columns = [];
        $dataFromId = [];
        foreach ($MyDatabase->fields as $columnId) {
            //print_r($column);continue;
            $column = ReportColumn::find($columnId);


            //$item->index = (string)$item->_id;
//print_r($column);exit;

            $item = [
//                'width' => 70,
                'type' => 'ed',
                'align' => 'left',
                'sort' => 'str',
                'value' => $column->title,
                'id' => $column->index,
            ];

            switch ($column->type) {
                case 'text':
                    $item['type'] = 'txt';
                    break;

                case 'number':
                    $item['type'] = 'edn';
                    //$item['setNumberFormat'] = 'edn';
                    break;



                case 'multiselect':
                    $item['type'] = 'clist';
                    $dataFromId[] = $column->index;
                    break;


                case 'checkbox':
                    $item['type'] = 'ch';
                    break;

                case 'date':
                    $item['type'] = 'dhxCalendarA';
                    break;

                case 'upload':
                    $item['type'] = 'upload';
                    break;

                case 'combo':
                    // Значит у нас хранятся айдишники и надо получать значение по айдишнику
                    $dataFromId[] = $column->index;
                    //$item['type'] = 'clist';

                    $item['type'] = 'combo';

                    $item['filter'] = 'true';
                    //$item['auto'] = 'true';
                    $item['source'] = '/report/database/getItems/'.$column->index;
                    break;

                default:
                    $item['type'] = 'ed';
                    break;
            }



            // sourceId
            if ($column->data) {

                $list = MyDatabase::findOrFail($column->data);
                ///print_r($list->items->toArray());exit;
                //$item->data = $list->items->ofContributorGroup(Session::get('contributorGroupId'));
                //$column->data = $list->items;
                $list = $list->items;
                $i = 1;
                foreach ($list as $v) {

/*
                    $item['options'][] = [
                        //'id'    => $v->_id,
                        //'value' => $v->name,
                        'value'    => "$i",

resources/views/my-database/create.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
    {{ trans('report-column-data.columns_data') }}
@endsection

@section('contentheader_title')
    {{ trans('report-column-data.columns_data') }}
@endsection

@section('js')
    <script type="text/javascript" src="{{asset('js/my-database.js')}}"></script>
@endsection

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-12">
                @if(Session::has('errors'))
                    <div class="callout callout-danger">
                        <h4>{{trans('global.errors')}}</h4>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ trans($error) }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{trans('report-column-data.create')}}</h3>
                        <div class="box-tools pull-right">
                            <a href="{{route('report.database.index')}}" class="btn btn-sm btn-primary">{{trans('report-column-data.cancel')}}</a>
                        </div>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'report.database.store']) !!}
                        <div class="box-body">
                            <div class="form-group">
                                {!! Form::label('name', trans('report-column-data.name')) !!}
                                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => trans('report-column-data.name-placeholder')]) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('fields', trans('report-template.fields')) !!}

                                {{ Form::sortable('fields', $fields, $selectedFields) }}
                            </div>

                        </div>
                        <div class="box-footer">
                            {!! Form::submit(trans('report-column-data.save'),['class' => 'btn btn-primary btn-flat btn-md']) !!}
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/my-database/edit.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
    {{ trans('report-column-data.columns_data') }}
@endsection

@section('contentheader_title')
    {{ trans('report-column-data.columns_data') }}
@endsection

@section('js')
    <script type="text/javascript" src="{{asset('js/my-database.js')}}"></script>
@endsection

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-12">
                @if(Session::has('errors'))
                    <div class="callout callout-danger">
                        <h4>{{trans('global.errors')}}</h4>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ trans($error) }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{trans('report-column-data.create')}}</h3>
                        <div class="box-tools pull-right">
                            <a href="{{route('report.database.index')}}" class="btn btn-sm btn-primary">{{trans('report-column-data.cancel')}}</a>
                        </div>
                    </div>
                    <div class="box-body">
                        {!!Form::model($model,['route' => ['report.database.update',  $model->getKey()], 'method' => 'put'])!!}
                        <div class="box-body">
                            <div class="form-group">
                                {!! Form::label('name', trans('report-column-data.name')) !!}
                                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => trans('report-column-data.name-placeholder')]) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('fields', trans('report-template.fields')) !!}

                                {{ Form::sortable('fields', $fields, $selectedFields) }}

                            </div>
                        </div>
                        <div class="box-footer">
                            {!! Form::submit(trans('report-column-data.save'),['class' => 'btn btn-primary btn-flat btn-md']) !!}
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/my-database/grid.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
    {{ trans('report-column-data.columns_data') }}
@endsection

@section('contentheader_title')
    {{ trans('report-column-data.columns_data') }}
@endsection

@section('js')
    <script src="{{asset('js/MyDatabaseEdit.js')}}"></script>
    <script src="{{asset('js/dhtmlx.js')}}"></script>
@endsection

@section('main-content')




    <div class="container-fluid spark-screen">
        <div class="row">
            {!! Form::hidden('db_id', $model->getKey()) !!}

            @foreach ($fieldsMultiselect as $field)

                {!! Form::hidden('columnIndex_'.$field['columnIndex'], json_encode($field['values']), ['class' => 'column-multiselect', 'data-column-index' => $field['columnIndex']])  !!}

            @endforeach

            <div class="col-md-12">
                <div class="form-group pull-right">

                </div>
            </div>
            <div class="col-md-12">
                <button onclick="addRow();">Add row</button>
                <button onclick="deleteRow();">Delete row</button>
                <div id="grid" style="width:100%; min-height: 500px;">

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/my-database/index.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
    {{ trans('report-column-data.columns_data') }}
@endsection

@section('contentheader_title')
    {{ trans('report-column-data.columns_data') }}
@endsection

@section('js')
    <script type="text/javascript" src="{{asset('js/my-database.js')}}"></script>
@endsection

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title"></h3>
                        <div class="box-tools pull-right">
                            <a href="{{route('report.database.create')}}" class="btn btn-sm btn-primary">{{trans('report-column-data.add_data')}}</a>
                        </div>
                    </div>
                    <div class="box-body">
                        <table class="table table-bordered table-hover dataTable" id="my-database-table">
                            <thead>
                            <tr>
                                <th>{{trans('report-column-data.name')}}</th>
                                <th class="table-actions" width="146">{{trans('report-column-data.actions')}}</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection