routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::group(['middleware' => 'auth'], function () {

    // Projects

    Route::get('project/index', 'ProjectController@index')->name('project.index');
    //Route::get('project/create', 'ProjectController@create')->name('project.create');
    Route::get('project/list', 'ProjectController@getList')->name('project.list');

    Route::resource('project', 'ProjectController', ['except' => ['show']]);


    // Users
    //Route::group(['middleware' => 'group:1'], function()
    //{
        Route::resource('user', 'UserController', ['except' => ['show']]);
    //});


    Route::get('user/get-list', 'UserController@getList')->name('user.get-list');
    Route::post('user/change-group', 'UserController@changeContributorGroup')->name('user.change-group');
    Route::post('user/change-project', 'UserController@changeProject')->name('user.change-project');

    // Groups
    Route::resource('group', 'GroupController', ['except' => ['show']]);
    Route::get('group/get-list', 'GroupController@getList')->name('group.get-list');



    Route::get('report-schedule/createMultiple', 'Report\ReportScheduleController@createMultiple');
//    Route::get('report-schedule', 'ReportScheduleController@index')->name('report_schedule.index');
    Route::get('report-schedule/report/{id}', 'ReportScheduleController@index')->name('report_schedule.index');
    Route::get('report-schedule/list', 'ReportScheduleController@getList')->name('report_schedule.list');
    Route::get('report-schedule/getMiniStat', 'Report\ReportScheduleController@getMiniStat');

    Route::resource('report-schedule', 'ReportScheduleController', ['except' => ['show']]);


    Route::namespace('Dashboard')->prefix('dashboard')->group(function () {

        Route::get('media', 'MediaController@index')->name('dashboard.media');
        Route::get('press', 'PressController@index')->name('dashboard.press');
        Route::get('test', 'MediaController@test');
        Route::resource('dashboard', 'DashboardController');

    });


    Route::namespace('Report')->prefix('report-schedule')->group(function () {

        //Reports
        Route::get('grid/{index}', 'ReportScheduleController@grid')->name('report-schedule/grid');
        Route::any('get-data', 'ReportScheduleController@getData')->name('report-schedule.get-data');
        Route::post('add-row', 'ReportScheduleController@addRow')->name('report-schedule.add-row');
        Route::post('remove-row', 'ReportScheduleController@removeRow')->name('report-schedule.remove-row');
        Route::post('insert-data', 'ReportScheduleController@insertData')->name('report-schedule.insert-data');
        Route::post('change-status/{id}', 'ReportScheduleController@changeStatus')->name('report-schedule.change-status');
        Route::post('generateNewRow', 'ReportScheduleController@generateNewRow');
        Route::any('getData/{reportSchedule_id}', 'ReportScheduleController@getData');

        Route::get('destroy/{id}', 'ReportScheduleController@destroy')->name('report-schedule.destroy');

    });


    Route::namespace('Report')->prefix('report')->group(function () {

        Route::get('/', 'ReportController@index')->name('report.index');
        Route::get('destroy/{id}', 'ReportController@destroy')->name('report.destroy');

        // Report
        Route::resource('report', 'ReportController', ['except' => ['index','show', 'edit','update']]);

        // Report columns
        Route::resource('column', 'ReportColumnController', ['as' => 'report','except' => ['show']]);
        Route::get('column/get-list', 'ReportColumnController@getList')->name('report.column.get-list');

        // Report columns lists
        Route::resource('database', 'MyDatabaseController', ['as' => 'report','except' => ['show']]);
        Route::get('database/get-list', 'MyDatabaseController@getList')->name('report.database.get-list');
        Route::get('database/fill/{id}', 'MyDatabaseController@fill')->name('report.database.fill');
        Route::post('database/get-data', 'MyDatabaseController@getData')->name('report.database.get-data');
        Route::post('database/insert-data', 'MyDatabaseController@insertData')->name('report.database.insert-data');
        Route::post('database/remove-row', 'MyDatabaseController@removeRow')->name('report.database.remove-row');
        Route::post('database/generateNewRow', 'MyDatabaseController@generateNewRow');

        Route::any('database/getItems/{field}', 'MyDatabaseController@getItems');


        Route::any('database/getData/{db_id}', 'MyDatabaseController@getData')->name('report.database.get-data');


        // Report templates
        Route::resource('template', 'ReportTemplateController', ['as' => 'report','except' => ['show']]);
        Route::get('template/get-list', 'ReportTemplateController@getList')->name('report.template.get-list');
    });

    Route::namespace('Report')->prefix('reportFinal')->group(function () {

        Route::get('/list', 'ReportFinalController@getList');
        Route::get('/addNew', 'ReportFinalController@addNew');
        Route::resource('/', 'ReportFinalController');

    });

    Route::namespace('Import')->prefix('import')->group(function () {


        Route::get('importMediaByContries', 'ImportMediaByCountriesController@importMediaByCountries');
    });

    Route::namespace('presentation')->prefix('presentation')->group(function () {

        Route::get('generatePresentation', 'IFA_Berlin_2017_Controller@init');
    });
});

app/Models/Report/ReportTemplate.php
<?php

namespace App\Models\Report;

use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;
//use Jenssegers\Mongodb\Eloquent\Model as Model;
use Yajra\Datatables\Facades\Datatables;
use Illuminate\Support\Facades\Validator;

class ReportTemplate extends \Moloquent
{
    use Sluggable, SluggableScopeHelpers;

    const MONTHLY_REPORT = 'monthly-report';

    protected $table = 'reports_templates';

    protected $fillable = ['name', 'fields', 'fields1'];


    private $rules = [
        'name' => 'required|max:255',
        'fields' => 'required',
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function getList()
    {
        $query = $this->select('*')->get();
        return $query;
    }

    public function datatables($data)
    {
        $editable = true;
        $deletable = true;

        return Datatables::of($data)
            ->addColumn('action', function ($item) use($editable, $deletable) {
                if($item->slug == $this::MONTHLY_REPORT)
                    $deletable = false;
                return $this->_generateActions($item, $editable, $deletable);
            })
            ->make(true);
    }

    public function validate($data)
    {
        if(!$data) {
            return false;
        }

        $v = Validator::make($data, $this->rules);
        $v->validate();
        if ($v->fails()) {
            return false;
        }
        return true;
    }

    private function _generateActions($item, $editable, $deletable)
    {
        $view = view('partials.table_actions', ['item' => $item, 'route' => 'report.template', 'editable' => $editable, 'deletable' => $deletable]);
        return $view->render();

    }
}

app/Http/Controllers/Report/ReportTemplateController.php
<?php

namespace App\Http\Controllers\Report;

use App\Http\Controllers\Controller;
use App\Models\Report\ReportColumn;
use App\Models\Report\ReportTemplate;
use Illuminate\Http\Request;
use Helper;


class ReportTemplateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('report_template.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //$fields = ReportColumn::pluck('title', '_id');

        $fields_tmp = ReportColumn::pluck('title', '_id');
        $fields = [];
        foreach ($fields_tmp as $k => $v) {
            $fields[] = [
                '_id' => $k,
                'title' => $v,
            ];
        }

        $data = [
            //'model' => $model,
            //'_id' => $model->_id,
            //'title' => $model->title,
            'fields' => $fields,
            'selectedFields' => []
        ];

        //return view('report_template.create',compact('fields'));
        return view('report_template.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /*
        $model = new ReportTemplate();
        $data = array();

        foreach ($request->all() as $key => $value){
            $data[$key] = is_array($value) ? $request->$key : htmlspecialchars( clean( $request->$key, 'noHtml'), ENT_QUOTES );
            $data[$key] = empty($data[$key]) ? null : $data[$key];
        }

        if ($model->validate($data))
            if($model->create($data))
                return redirect()->route('report.template.index');
*/

        $model = new ReportTemplate();
        $model->name = $request->input('name');
        $model->fields = explode('|', $request->input('selectedFields_ser'));

        //echo Helper::shout('now i\'m using my helper class in a controller!!');

        $model->save();
        return redirect()->route('report.template.index');







    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = ReportTemplate::findOrFail($id);
        //$fields = ReportColumn::pluck('title', '_id');

        //return view('report_template.edit',compact(['model','fields']));


        $fields_tmp = ReportColumn::pluck('title', '_id');
        $fields = [];
        foreach ($fields_tmp as $k => $v) {
            $fields[] = [
                '_id' => $k,
                'title' => $v,
            ];
        }

/*
        $fieldsStr = [];
        foreach ($model->fields as $f) {
            $fieldsStr[] = (string)$f;
        }*/

        $selectedFields_tmp = ReportColumn::whereIn('_id', $model->fields)->get();


        $selectedFields_tmp = Helper::getMongoArray($selectedFields_tmp, '_id');


        $selectedFields = [];
        foreach ($model->fields as $fieldId) {
            $selectedFields[] = $selectedFields_tmp[$fieldId];

            // Нужно удалить из списка те, которые уже выбраны, чтобы они не были дважды
            //unset($fields[$f->_id]);

            foreach ($fields as $key2 => $subArr2) {
                if ($subArr2['_id'] == $fieldId) {
                    unset($fields[$key2]);
                }

            }

        }


/*

        $selectedFields = [];
        foreach ($selectedFields_tmp as $f) {
            $selectedFields[$f->_id] = $f->title;

            // Нужно удалить из списка те, которые уже выбраны, чтобы они не были дважды
            unset($fields[$f->_id]);
        }
*/


        //print_r($selectedFields->toArray());exit;

        //print_r($fields);exit;


        //$fields = ['a'];
        //$selectedFields = $model->fields;

        $data = [
            'model' => $model,
            '_id' => $model->_id,
            'title' => $model->title,
            'fields' => $fields,
            'selectedFields' => $selectedFields
        ];
        return view('report_template.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {



        $model = ReportTemplate::findOrFail($id);


        /*
         * $data = array();
        foreach ($request->all() as $key => $value){
            $data[$key] = is_array($value) ? $request->$key : htmlspecialchars( clean( $request->$key, 'noHtml'), ENT_QUOTES );
            $data[$key] = empty($data[$key]) ? null : $data[$key];
        }
*/


        $model->name = $request->input('name');
        $model->fields = explode('|', $request->input('selectedFields_ser'));

        //echo Helper::shout('now i\'m using my helper class in a controller!!');

        $model->save();
        return redirect()->route('report.template.index');

        if ($model->validate($data))
            if($model->save($data))
                return redirect()->route('report.template.index');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = ReportTemplate::findOrFail($id);

        if($model->delete())
            return redirect()->route('report.template.index');
    }

    /**
     * Get data for datatable.
     *
     * @return \Illuminate\Http\Response
     */
    public function getList()
    {
        $model = new ReportTemplate();
        $data = $model->getList();

        return $model->datatables($data);
    }
}

resources/views/report_template/create.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
    {{ trans('report-template.report_template') }}
@endsection

@section('contentheader_title')
    {{ trans('report-template.report_template') }}
@endsection

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            @if(empty($fields))
                <div class="col-md-12">
                    <div class="box box-solid box-danger">
                        <div class="box-header">
                            <h3 class="box-title">{{trans('global.warning')}}</h3>
                        </div>
                        <div class="box-body">
                            {{trans('report-template.add-column-warning')}}
                        </div>
                    </div>
                </div>
            @endif
            <div class="col-md-12">
                @if(Session::has('errors'))
                    <div class="callout callout-danger">
                        <h4>{{trans('global.errors')}}</h4>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ trans($error) }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{trans('report-template.create')}}</h3>
                        <div class="box-tools pull-right">
                            <a href="{{route('report.template.index')}}" class="btn btn-sm btn-primary">{{trans('report-template.cancel')}}</a>
                        </div>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'report.template.store']) !!}
                        <div class="box-body">
                            <div class="form-group">
                                {!! Form::label('name', trans('report-template.name')) !!}
                                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => trans('report-template.name-placeholder')]) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('fields', trans('report-template.fields')) !!}

                                {{ Form::sortable('fields', $fields, $selectedFields) }}
                            </div>
                        </div>
                        <div class="box-footer">
                            {!! Form::submit(trans('report-template.save'),['class' => 'btn btn-primary btn-flat btn-md']) !!}
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/report_template/edit.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
    {{ trans('report-template.report_template') }}
@endsection

@section('contentheader_title')
    {{ trans('report-template.report_template') }}
@endsection

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            @if(empty($fields))
                <div class="col-md-12">
                    <div class="box box-solid box-danger">
                        <div class="box-header">
                            <h3 class="box-title">{{trans('global.warning')}}</h3>
                        </div>
                        <div class="box-body">
                            {{trans('report-template.add-column-warning')}}
                        </div>
                    </div>
                </div>
            @endif
            <div class="col-md-12">
                @if(Session::has('errors'))
                    <div class="callout callout-danger">
                        <h4>{{trans('global.errors')}}</h4>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ trans($error) }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{trans('report-template.create')}}</h3>
                        <div class="box-tools pull-right">
                            <a href="{{route('report.template.index')}}" class="btn btn-sm btn-primary">{{trans('report-template.cancel')}}</a>
                        </div>
                    </div>
                    <div class="box-body">
                        {!!Form::model($model,['route' => ['report.template.update',  $model->getKey()], 'method' => 'put'])!!}
                        <div class="box-body">
                            <div class="form-group">
                                {!! Form::label('name', trans('report-template.name')) !!}
                                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => trans('report-template.name-placeholder')]) !!}
                            </div>
                            <div class="form-group">
                                {!! Form::label('fields', trans('report-template.fields')) !!}

                                {{ Form::sortable('fields', $fields, $selectedFields) }}

                            </div>
                        </div>
                        <div class="box-footer">
                            {!! Form::submit(trans('report-template.save'),['class' => 'btn btn-primary btn-flat btn-md']) !!}
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/report_template/index.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
    {{ trans('report-template.report_template') }}
@endsection

@section('contentheader_title')
    {{ trans('report-template.report_template') }}
@endsection

@section('js')
    <script type="text/javascript" src="{{asset('js/report-template.js')}}"></script>
@endsection

@section('main-content')

    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-md-12">
                @if (session('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title"></h3>
                        <div class="box-tools pull-right">
                            <a href="{{route('report.template.create')}}" class="btn btn-sm btn-primary">{{trans('report-template.add_type')}}</a>
                        </div>
                    </div>
                    <div class="box-body">
                        <table class="table table-bordered table-hover dataTable" id="report-templates-table">
                            <thead>
                            <tr>
                                <th>{{trans('report-template.name')}}</th>
                                <th class="table-actions">{{trans('report-column.actions')}}</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection